config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :customers, controllers: {
    sessions: 'sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'    
  }

  namespace :customers do
    root to: 'products#top'
    get '/about' => 'products#about'
    get '/products' => 'products#index'
    get 'products/:id' => 'products#show'
  end

  namespace :admins do
    resources :products, only: [:new, :create, :index, :edit, :update, :show]
    # get 'products/index'
    # get 'products/new'
    # get 'products/show'
    # get 'products/edit'
  end
  
end

app/models/product.rb
class Product < ApplicationRecord

attachment :image

end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to admins_product_path(@product.id)
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    rediredt_to admins_product_path(@product.id)
  end
  
  private
  
  def product_params
    params.require(:produt).permit(:image, :name, :detail, :category_id, :price, :product_status)
  end
end

app/controllers/customers/products_controller.rb
class Customers::ProductsController < ApplicationController
  def top
    @product = Product.order("id DESC")
  end

  def about
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/customers/products_helper.rb
module Customers::ProductsHelper
end

app/views/admins/products/edit.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-left">商品新規登録</h3>
    <%= form_with model:@product, local:true do |f| %>
      <table>
        <tr>
          <td>商品画像</td>
          <td><%= f.attachment_field :image %></td>
        </tr>
        <tr>
          <td>商品名</td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= f.text_field :detail %></td>
        </tr>
          <tr>
          <td>ジャンル</td>
          <td><%= f.collection_select :category_id, @cotegory.all, :id, :name, include_blank: "選択" %></td>
        </tr>
        <tr>
          <td>税抜価格</td>
          <td><%= f.number_field :price %></td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <%= f.radio_button :product_status, :true %>
            <%= f.label :product_status, "販売中", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :product_status, :false %>
            <%= f.label :product_status, "販売停止中", {value: :false, style: "display: inline-block;"} %>
          </td>
        </tr>
      </table>
      <%= f.submit '変更を' %>
    <% end %>  
    </div>
  </div>

app/views/admins/products/index.html.erb
<div class="container">
    <div class="row">
        <div class ="col-lg-12">
          <h3>商品一覧</h3>
              <table class = "table table-hover">
                <thead>
                  <tr>
                    <th>商品ID</th>
                    <th>商品名</th>
                    <th>税抜価格</th>
                    <th>ジャンル</th>
                    <th>ステータス</th>
                  </tr>
                </thead>
                <tbody>
                  <% @product.each do |product| %>
                  <tr>
                    <td><%= product.id %></td>
                    <td><%= link_to product.name,"admins/products/#{product.id}" %></td>
                    <td><%= product.price %></td>
                    <td><%= product.category_id %></td>
                    <td><%= product.product_status  %></td>
                    <th>
                  </tr>
                  <% end %>
                </tbody>
              </table>
        </div>
    </div>
</div>

app/views/admins/products/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-left">商品新規登録</h3>
    <%= form_with model@product, local:true do |f| %>
      <table>
        <tr>
          <td>商品画像</td>
          <td><%= f.attachment_field :image %></td>
        </tr>
        <tr>
          <td>商品名</td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= f.text_field :detail %></td>
        </tr>
          <tr>
          <td>ジャンル</td>
          <td><%= f.collection_select :category_id, @cotegory.all, :id, :name, include_blank: "選択してください" %></td>
        </tr>
        <tr>
          <td>税抜価格</td>
          <td><%= f.number_field :price %>円</td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <%= f.radio_button :product_status, :true %>
            <%= f.label :product_status, "販売中", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :product_status, :false %>
            <%= f.label :product_status, "販売停止中", {value: :false, style: "display: inline-block;"} %>
          </td>
        </tr>
      </table>
      <%= f.submit '新規登録' %>
    <% end %>  
    </div>
  </div>
 

app/views/admins/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h3>商品詳細</h3>
      <div>
        <%= attachment_image_tag @product, :image, :fill, 100, 100, fallback: "no_image.jpg", size:'30x30' %>
      </div>
      
      <div>
        <table>
        <tr>
          <td>商品名</td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @producr.detail %></td>
        </tr>
          <tr>
          <td>ジャンル</td>
          <td><%= @product.category_id %></td>
        </tr>
        <tr>
          <td>税抜価格<br>(税込価格)</td>
          <td><%= @product.price %>円</td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <%= @produt.product_status %>
          </td>
        </tr>
      </table>
      <%= link_to '編集する',  edit_admins_product_path(@book.id), class: "btn btn-success btn-sm" %>
    </div>
        
        
    </div>
  </div>
 </div>